### ISSUE TITLE
Ability to set peer endpoint

### ISSUE THREAD

**Issue by hmrodrigues** [inloco/pywireguard#1]
Hello,

Please add the ability to set the peer endpoint via the Peer class.

Thank you

**Comment by PauloLuna** [comment]
Hi, I believe this is an interesting issue and I will add it to the project.
Anyway, I saw your issue on wg-manager and I feel compelled to tell you to take a look at this library
https://docs.pyroute2.org/wireguard.html

**Comment by hmrodrigues** [comment]
Thanks, I will take a look
